//! build.rs — 读取 abi-version.txt，生成 Python 侧 `_rust_abi.py`。
//!
//! 单一来源：`crates/e2m2e-integrators/abi-version.txt`。
//! Rust 侧 `lib.rs` 通过 `include_str!` 读同一文件；本脚本在
//! `cargo build` / `maturin develop` 时生成 `e2m2e/_rust_abi.py`，
//! 供 Python 侧 import 获取版本号。

use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let version_file = manifest_dir.join("abi-version.txt");

    println!("cargo:rerun-if-changed={}", version_file.display());

    let version_str = match fs::read_to_string(&version_file) {
        Ok(s) => s.trim().to_string(),
        Err(e) => {
            println!("cargo:warning=build.rs: cannot read abi-version.txt: {e}");
            return;
        }
    };

    // 验证内容是纯数字
    if version_str.is_empty() || !version_str.bytes().all(|b| b.is_ascii_digit()) {
        println!(
            "cargo:warning=build.rs: abi-version.txt content is not a valid integer: {version_str:?}"
        );
        return;
    }

    // 输出路径：相对于 CARGO_MANIFEST_DIR 往上两级到仓库根的 e2m2e/ 目录
    let out_path = manifest_dir
        .parent() // crates/
        .and_then(|p| p.parent()) // repo root
        .map(|p| p.join("e2m2e").join("_rust_abi.py"));

    let out_path = match out_path {
        Some(p) => p,
        None => {
            println!("cargo:warning=build.rs: cannot resolve e2m2e/_rust_abi.py path");
            return;
        }
    };

    let content = format!(
        "# Auto-generated by build.rs -- do not edit manually.\n\
         # Single source of truth: crates/e2m2e-integrators/abi-version.txt\n\
         _ABI_VERSION: int = {version_str}\n"
    );

    if let Err(e) = fs::write(&out_path, content) {
        println!(
            "cargo:warning=build.rs: cannot write {}: {e}",
            out_path.display()
        );
    }
}
