[package]
name = "e2m2e-integrators"
version = "0.1.0"
edition = "2021"

[lib]
name = "e2m2e_integrators"
crate-type = ["cdylib", "rlib"]

[features]
default = []
spice = ["dep:cspice", "dep:cspice-sys", "e2m2e-forces/spice", "e2m2e-spice/spice"]

[dependencies]
pyo3 = { workspace = true }
e2m2e-propagation = { path = "../e2m2e-propagation" }
e2m2e-forces = { path = "../e2m2e-forces" }
e2m2e-spice = { path = "../e2m2e-spice" }
cspice = { workspace = true, optional = true }
cspice-sys = { workspace = true, optional = true }
