"""生成与 e2m2e LEO 传播对齐的 GMAT 脚本。

当前环境未安装可运行的 GMAT 二进制，本脚本只负责生成 `.script` 文件
并返回调用命令；运行 GMAT 后可用 ``compare_with_gmat.py`` 做对比。
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any


# 默认基准与 issue #70 决议一致：400 km 高度、51.6° 倾角、历元 2025-06-21T11:00:06
DEFAULT_KEPLERIAN = {
    "semi_major_axis_km": 6778.0,  # 400 km altitude
    "eccentricity": 0.001,
    "inclination_deg": 51.6,
    "raan_deg": 0.0,
    "arg_of_perigee_deg": 0.0,
    "true_anomaly_deg": 0.0,
}

DEFAULT_SPACECRAFT = {
    "mass_kg": 1000.0,
    "cd": 2.2,
    "cr": 1.4,
    "drag_area_m2": 10.0,
    "srp_area_m2": 10.0,
}

DEFAULT_FORCEMODEL = {
    "gravity_degree": 10,
    "gravity_order": 10,
    "gravity_potential_file": "EGM96.cof",
    "drag_model": "Exponential",
    "f107": 150.0,
    "ap": 4.0,
    "srp": True,
    "shadow_bodies": None,
}

DEFAULT_PROPAGATOR = {
    "type": "RungeKutta89",
    "initial_step": 60.0,
    "accuracy": 1e-13,
    "min_step": 1e-15,
    "max_step": 60.0,
    "max_step_attempts": 50,
}

DEFAULT_MISSION = {
    "epoch_utc": "2025-06-21T11:00:06",
    "elapsed_days": 1.0,
    "report_interval_sec": 60.0,
}


def generate_gmat_script(
    output_dir: str | Path,
    *,
    spacecraft: dict[str, Any] | None = None,
    keplerian: dict[str, Any] | None = None,
    forcemodel: dict[str, Any] | None = None,
    propagator: dict[str, Any] | None = None,
    mission: dict[str, Any] | None = None,
) -> Path:
    """生成 GMAT 脚本并返回脚本路径。

    Args:
        output_dir: 输出目录，脚本与报告文件都写在这里。
        spacecraft: 航天器物理参数。
        keplerian: 初始轨道根数（a/e/i/RAAN/argp/true anomaly）。
        forcemodel: 力模型配置。
        propagator: 积分器配置。
        mission: 任务配置（历元、传播时长、报告间隔）。

    Returns:
        生成的 `.script` 文件路径。
    """
    output_dir = Path(output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    sc = {**DEFAULT_SPACECRAFT, **(spacecraft or {})}
    kep = {**DEFAULT_KEPLERIAN, **(keplerian or {})}
    fm = {**DEFAULT_FORCEMODEL, **(forcemodel or {})}
    prop = {**DEFAULT_PROPAGATOR, **(propagator or {})}
    mission_cfg = {**DEFAULT_MISSION, **(mission or {})}

    script_path = output_dir / "leo_reference_gmat.script"
    report_file = output_dir / "leo_reference_gmat_report.txt"

    sc_name = "LEOSat"
    fm_name = "LEOForceModel"
    prop_name = "LEOPropagator"
    rf_name = "LEOReport"

    # 避免 windows 反斜杠：GMAT 接受正斜杠
    report_file_str = str(report_file).replace("\\", "/")

    lines: list[str] = []
    lines.append("%")
    lines.append("%  GMAT LEO reference script generated by e2m2e")
    lines.append("%  CoordinateSystem: EarthICRF")
    lines.append("%  Force model: J2(deg={},ord={}) + {} drag + SRP={}".format(
        fm["gravity_degree"], fm["gravity_order"], fm["drag_model"], fm["srp"]
    ))
    lines.append("%")
    lines.append("")

    # Spacecraft
    lines.append("%----------------------------------------")
    lines.append("%---------- Spacecraft")
    lines.append("%----------------------------------------")
    lines.append("")
    lines.append(f"Create Spacecraft {sc_name};")
    lines.append("")
    lines.append(f"{sc_name}.DateFormat       = UTCGregorian;")
    lines.append(f"{sc_name}.Epoch            = '{mission_cfg['epoch_utc']}';")
    lines.append(f"{sc_name}.CoordinateSystem = EarthICRF;")
    lines.append(f"{sc_name}.DisplayStateType = Keplerian;")
    lines.append(f"{sc_name}.SMA              = {kep['semi_major_axis_km']};")
    lines.append(f"{sc_name}.ECC              = {kep['eccentricity']};")
    lines.append(f"{sc_name}.INC              = {kep['inclination_deg']};")
    lines.append(f"{sc_name}.RAAN             = {kep['raan_deg']};")
    lines.append(f"{sc_name}.AOP              = {kep['arg_of_perigee_deg']};")
    lines.append(f"{sc_name}.TA               = {kep['true_anomaly_deg']};")
    lines.append(f"{sc_name}.DryMass          = {sc['mass_kg']};")
    lines.append(f"{sc_name}.Cd               = {sc['cd']};")
    lines.append(f"{sc_name}.Cr               = {sc['cr']};")
    lines.append(f"{sc_name}.DragArea         = {sc['drag_area_m2']};")
    lines.append(f"{sc_name}.SRPArea          = {sc['srp_area_m2']};")
    lines.append("")

    # Force model
    lines.append("%----------------------------------------")
    lines.append("%---------- ForceModels")
    lines.append("%----------------------------------------")
    lines.append("")
    lines.append(f"Create ForceModel {fm_name};")
    lines.append("")
    lines.append(f"{fm_name}.CentralBody                            = Earth;")
    lines.append(f"{fm_name}.PrimaryBodies                          = {{Earth}};")
    lines.append(f"{fm_name}.GravityField.Earth.Degree              = {fm['gravity_degree']};")
    lines.append(f"{fm_name}.GravityField.Earth.Order               = {fm['gravity_order']};")
    lines.append(
        f"{fm_name}.GravityField.Earth.PotentialFile       = '{fm['gravity_potential_file']}';"
    )
    lines.append(f"{fm_name}.GravityField.Earth.TideModel           = 'None';")

    if fm["drag_model"] == "Exponential":
        lines.append(f"{fm_name}.Drag                                   = Exponential;")
        lines.append(f"{fm_name}.AtmosphereModel                        = Exponential;")
        lines.append(f"% {fm_name}.AtmosphereModel.F107 = {fm['f107']};")
        lines.append(f"% {fm_name}.AtmosphereModel.MagneticIndex = {fm['ap']};")
    else:
        lines.append(f"{fm_name}.Drag                                   = None;")

    if fm["srp"]:
        lines.append(f"{fm_name}.SRP                                    = On;")
        lines.append(f"{fm_name}.SRP.SRPModel                           = Spherical;")
        lines.append(f"{fm_name}.SRP.Flux                               = 1367;")
        lines.append(f"{fm_name}.SRP.Nominal_Sun                        = 149597870.7;")
        lines.append(f"{fm_name}.SRP.ShadowModel                        = None;")
    else:
        lines.append(f"{fm_name}.SRP                                    = Off;")

    lines.append("")

    # Propagator
    lines.append("%----------------------------------------")
    lines.append("%---------- Propagators")
    lines.append("%----------------------------------------")
    lines.append("")
    lines.append(f"Create Propagator {prop_name};")
    lines.append("")
    lines.append(f"{prop_name}.FM                  = {fm_name};")
    lines.append(f"{prop_name}.Type                = {prop['type']};")
    lines.append(f"{prop_name}.InitialStepSize     = {prop['initial_step']};")
    lines.append(f"{prop_name}.Accuracy            = {prop['accuracy']};")
    lines.append(f"{prop_name}.MinStep             = {prop['min_step']};")
    lines.append(f"{prop_name}.MaxStep             = {prop['max_step']};")
    lines.append(f"{prop_name}.MaxStepAttempts     = {prop['max_step_attempts']};")
    lines.append("")

    # Report file
    lines.append("%----------------------------------------")
    lines.append("%---------- Subscribers")
    lines.append("%----------------------------------------")
    lines.append("")
    lines.append(f"Create ReportFile {rf_name};")
    lines.append("")
    lines.append(f"{rf_name}.Filename     = '{report_file_str}';")
    lines.append(f"{rf_name}.WriteHeaders = true;")
    lines.append(f"{rf_name}.LeftJustify  = On;")
    lines.append(f"{rf_name}.Delimiter    = ' ';")
    lines.append(f"{rf_name}.Precision    = 16;")
    lines.append(f"{rf_name}.Add = {{{sc_name}.UTCGregorian, ...")
    lines.append(f"    {sc_name}.EarthICRF.X, {sc_name}.EarthICRF.Y, {sc_name}.EarthICRF.Z, ...")
    lines.append(f"    {sc_name}.EarthICRF.VX, {sc_name}.EarthICRF.VY, {sc_name}.EarthICRF.VZ}};")
    lines.append("")

    # Mission sequence
    lines.append("%----------------------------------------")
    lines.append("%---------- Mission Sequence")
    lines.append("%----------------------------------------")
    lines.append("")
    lines.append("BeginMissionSequence")
    lines.append("")
    lines.append(f"{rf_name}.WriteReport = true;")
    elapsed_days = float(mission_cfg["elapsed_days"])
    lines.append(f"Propagate {prop_name}({sc_name}) {{{sc_name}.ElapsedDays = {elapsed_days}}};")
    lines.append("")

    script_path.write_text("\n".join(lines), encoding="utf-8")
    return script_path


def build_gmat_command(script_path: str | Path, gmat_executable: str | Path | None = None) -> str:
    """返回调用 GMAT 的命令字符串。"""
    script_path = Path(script_path).expanduser().resolve()
    if gmat_executable is None:
        return f"gmat -s {script_path}"
    return f"{Path(gmat_executable)} -s {script_path}"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a GMAT script for LEO propagation aligned with e2m2e."
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="./gmat_leo_output",
        help="Directory for the generated script and GMAT report file.",
    )
    parser.add_argument(
        "--gmat-exe",
        type=str,
        default=None,
        help="Path to GMAT executable. If omitted, prints a generic command.",
    )
    args = parser.parse_args()

    script_path = generate_gmat_script(args.output_dir)
    command = build_gmat_command(script_path, args.gmat_exe)

    print(f"Generated GMAT script: {script_path}")
    print(f"Run with: {command}")


if __name__ == "__main__":
    main()
